cors:
  originPatterns: http://localhost:8080,http://localhost:3000,https://www.erudio.com.br
security:
  jwt:
    token:
      secret-key: 53cr37
      expire-lenght: 3600000

spring:
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
  datasource:
    url: jdbc:postgresql://localhost:5432/auth
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
