server:
  port: 8082

internal:
  token: c523db8c7dafcaf567a28d7d910f985ffdfff52d2e5850f18062f8c82e338e6b
  key: X-Internal-Token
security:
  jwt:
    token:
      secret-key: uH12jPqz0W+o+fSde9q5Tf0mXEtmCqKnm2Vp3xczxUg=
      expire-lenght: 3600000

spring:
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
  datasource:
    url: jdbc:postgresql://localhost:5432/auth
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
